"""Standalone local Hermes-inspired agent controller."""

from .agent_evolution import (
    AgentCandidateEvaluator,
    AgentCandidateGenerator,
    AgentEvaluatorEnsemble,
    AgentPortfolioGenerator,
)
from .agents import (
    AgentAdapter,
    AgentError,
    AgentInvocationError,
    AgentRegistry,
    AgentRequest,
    AgentResult,
    AgentSelectionError,
    CandidateGenerationBudget,
    CandidateGenerationDiagnostic,
    CommandAgentAdapter,
    RuntimeAgentAdapter,
)
from .algorithm import OutputSpec
from .benchmark import (
    ACTIVE_BENCHMARK_STRATEGIES,
    BENCHMARK_STRATEGIES,
    BenchmarkConfig,
    BenchmarkError,
    BenchmarkReport,
    BenchmarkRun,
    BenchmarkRunner,
)
from .benchmark_comparison import (
    AdmittedBenchmarkComparison,
    BenchmarkComparisonError,
    BenchmarkComparisonPlan,
    ComparisonArm,
    admit_benchmark_comparison_plan,
    parse_benchmark_comparison_plan,
    validate_benchmark_comparison_plan,
)
from .benchmark_result import (
    BenchmarkComparisonResult,
    BenchmarkResultError,
    ComparisonArmResult,
    admit_benchmark_comparison_result,
    bind_benchmark_comparison_result_evidence,
    parse_benchmark_comparison_result,
)
from .benchmark_task import (
    BENCHMARK_TASK_PROTOCOL,
    BENCHMARK_TASK_SCHEMA_VERSION,
    AdmittedBenchmarkTask,
    BenchmarkTaskEnvelope,
    BenchmarkTaskError,
    ModelIdentity,
    PhysicalAttemptBudget,
    TaskIdentity,
    TaskInput,
    admit_benchmark_task_envelope,
    parse_benchmark_task_envelope,
)
from .benchmark_task import (
    EvaluatorIdentity as BenchmarkTaskEvaluatorIdentity,
)
from .bundle_delivery import BundleDeliveryResult, inspect_bundle_delivery
from .bundle_evolution import (
    MultiFileCandidatePipeline,
    load_bundle_pipeline,
    read_bundle_delivery_materials,
    read_candidate_source_files,
)
from .candidate_bundle import (
    CANDIDATE_BUNDLE_PROTOCOL,
    CANDIDATE_BUNDLE_SCHEMA_VERSION,
    CandidateBundleError,
    CandidateSourceBundle,
    CandidateSourceFile,
    VerifiedCandidateSourceBundle,
    parse_candidate_source_bundle,
    validate_candidate_source_bundle,
    verify_candidate_source_bundle,
)
from .candidate_evaluation import (
    CandidateEvaluationResult,
    evaluate_candidate_execution,
    inspect_candidate_evaluation,
)
from .candidate_evaluation_spec import (
    CandidateEvaluationError,
    CandidateEvaluationSpec,
    candidate_output_contract_sha256,
    parse_candidate_evaluation_report,
    parse_candidate_evaluation_spec,
)
from .candidate_execution import (
    CANDIDATE_EXECUTION_PROTOCOL,
    CANDIDATE_EXECUTION_SCHEMA_VERSION,
    EXECUTION_PROTOCOL,
    EXECUTION_SCHEMA_VERSION,
    CandidateEvaluatorPin,
    CandidateExecutionAdmission,
    CandidateExecutionBudget,
    CandidateExecutionError,
    CandidateExecutionInput,
    VerifiedCandidateExecutionAdmission,
    admit_candidate_execution,
    admit_candidate_execution_admission,
    build_candidate_execution_admission,
    parse_candidate_execution_admission,
    validate_candidate_execution_admission,
)
from .candidate_execution_evidence import (
    CandidateExecutionEvidenceError,
    CandidateExecutionRecord,
    inspect_candidate_execution_record,
    run_candidate_execution_recorded,
)
from .candidate_execution_runner import (
    CANDIDATE_INPUT_ROOT_ENV,
    CandidateExecutionRun,
    CandidateExecutionRunner,
    CandidateExecutionRunnerError,
    run_candidate_execution,
)
from .candidate_input_staging import (
    CandidateInputStagingError,
    StagedCandidateExecutionInputs,
    stage_candidate_execution_inputs,
)
from .candidate_workspace import (
    WORKSPACE_PLAN_PROTOCOL,
    WORKSPACE_PLAN_SCHEMA_VERSION,
    CandidateWorkspaceError,
    CandidateWorkspacePlan,
    VerifiedCandidateWorkspace,
    build_candidate_workspace_plan,
    candidate_file_table_sha256,
    materialize_candidate_source_bundle,
    parse_candidate_workspace_plan,
    validate_candidate_workspace_plan,
)
from .conversational import (
    CallableContractCompiler,
    CompilationQuestion,
    CompilationResult,
    ContractCompilationError,
    ContractCompiler,
    RuntimeContractCompiler,
    build_algorithm_plan,
    build_algorithm_role_plan,
)
from .data_profile import (
    DataProfileError,
    build_private_input_profile,
    canonical_profile_json,
    profile_sha256,
)
from .deep_effect_trial import DeepEffectTrialConfig, DeepEffectTrialRunner
from .deep_feedback import (
    FeedbackError,
    build_candidate_manifest,
    build_round_feedback,
    normalize_feedback,
)
from .effect_adapters import (
    EffectAdapterError,
    benchmark_case_content_digest,
    convert_fm_eval_baseline,
    run_harness_adapter,
    run_subject_adapter,
)
from .effect_kit import EffectKitError, build_effect_kit
from .effect_preflight import (
    EffectPreflightError,
    EffectPreflightReport,
    EffectPreflightRunner,
    run_effect_preflight,
)
from .effect_trial import (
    BaselineProvenance,
    EffectTrialConfig,
    EffectTrialError,
    EffectTrialReport,
    EffectTrialRunner,
    TrialBaseline,
    TrialSuite,
)
from .evaluator_bundle import (
    EvaluatorBundleError,
    FrozenEvaluatorBundle,
    SolverScoringContract,
    compile_evaluator_bundle,
    load_evaluator_bundle,
)
from .evolution import (
    Candidate,
    CandidateArchive,
    CandidateDraft,
    CandidateExecution,
    CandidateInputArtifact,
    CandidateIntegrityAuthority,
    CandidateReceipt,
    CandidateRunner,
    CommandCandidateEvaluator,
    CommandCandidateGenerator,
    CommandCandidateRunner,
    ContractCandidateRunner,
    EvolutionConfig,
    EvolutionContext,
    EvolutionError,
    EvolutionStrategy,
    ExecutionAwareCandidateEvaluator,
    GenerationRequest,
    LoopStrategy,
    OffspringOutcome,
    OpenEvolveStrategy,
    PopulationConfig,
    PopulationState,
    PopulationStrategy,
    StrategyResult,
    build_strategy,
    config_from_contract,
    contract_candidate_runner_fingerprint,
    resolve_candidate_integrity_authority,
    stage_candidate_inputs,
)
from .model_profile import UsageLedger, UsageSnapshot
from .models import Worker, WorkerAttempt, WorkerOutcome, WorkerPhase, WorkerStopReason
from .openevolve_handoff import (
    OpenEvolveHandoffError,
    admit_openevolve_result,
    declared_protocol_environment_sha256,
    source_only_dependency_sha256,
)
from .producer_handoff import (
    ProducerHandoffError,
    ProducerMaterial,
    ProducerResultEnvelope,
    admit_producer_envelope,
    admit_producer_result,
    declared_producer_environment_sha256,
    parse_producer_envelope,
    prepare_producer_seed_manifest,
    producer_bundle_dependency_sha256,
)
from .profiles import EvaluatorProfile, ModelProfile, ProfileRegistry, SolverProfile
from .remote_evolution import (
    RemoteCancelRequest,
    RemoteContinueRequest,
    RemoteEvolutionBackend,
    RemoteEvolutionError,
    RemoteExperimentReference,
    RemoteExperimentState,
    RemoteMaterialReference,
    RemoteStatusRequest,
    RemoteSubmitRequest,
    RemoteSyncRequest,
    reconcile_remote_state,
)
from .remote_evolution import (
    cancel as remote_cancel,
)
from .remote_evolution import (
    continue_experiment as remote_continue_experiment,
)
from .remote_evolution import (
    status as remote_status,
)
from .remote_evolution import (
    submit as remote_submit,
)
from .remote_evolution import (
    sync as remote_sync,
)
from .remote_material_handoff import (
    RemoteMaterialHandoffError,
    admit_remote_materials,
    admit_remote_state,
    build_remote_producer_envelope,
    remote_state_to_producer_envelope,
)
from .seed_handoff import (
    AdmittedSeed,
    EvaluatorIdentity,
    EvaluatorReceipt,
    RejectedSeed,
    SeedAdmissionError,
    SeedAdmissionResult,
    SeedIdentity,
    SeedManifest,
    SeedProvenance,
    SeedRecord,
    admit_seed_manifest,
    compute_handoff_fingerprint,
    compute_seed_identity,
    parse_seed_manifest,
)
from .shinka_handoff import (
    ShinkaHandoffError,
    export_shinka_envelope,
    export_shinka_result,
)
from .staged_workflow import (
    StagedRunResult,
    StagedWorkflowConfig,
    StagedWorkflowRunner,
    StagePolicy,
)
from .workers import WorkerService
from .workflow_checkpoint import (
    AggregateUsage,
    Checkpoint,
    WorkflowCheckpoint,
    WorkflowCheckpointError,
    WorkflowController,
    WorkflowError,
    WorkflowManifest,
    WorkflowState,
)

__version__ = "0.1.0"

__all__ = [
    "ACTIVE_BENCHMARK_STRATEGIES",
    "BENCHMARK_STRATEGIES",
    "BENCHMARK_TASK_PROTOCOL",
    "BENCHMARK_TASK_SCHEMA_VERSION",
    "CANDIDATE_BUNDLE_PROTOCOL",
    "CANDIDATE_BUNDLE_SCHEMA_VERSION",
    "CANDIDATE_EXECUTION_PROTOCOL",
    "CANDIDATE_EXECUTION_SCHEMA_VERSION",
    "CANDIDATE_INPUT_ROOT_ENV",
    "EXECUTION_PROTOCOL",
    "EXECUTION_SCHEMA_VERSION",
    "WORKSPACE_PLAN_PROTOCOL",
    "WORKSPACE_PLAN_SCHEMA_VERSION",
    "AdmittedBenchmarkComparison",
    "AdmittedBenchmarkTask",
    "AdmittedSeed",
    "AgentAdapter",
    "AgentCandidateEvaluator",
    "AgentCandidateGenerator",
    "AgentError",
    "AgentEvaluatorEnsemble",
    "AgentInvocationError",
    "AgentPortfolioGenerator",
    "AgentRegistry",
    "AgentRequest",
    "AgentResult",
    "AgentSelectionError",
    "AggregateUsage",
    "BaselineProvenance",
    "BenchmarkComparisonError",
    "BenchmarkComparisonPlan",
    "BenchmarkComparisonResult",
    "BenchmarkConfig",
    "BenchmarkError",
    "BenchmarkReport",
    "BenchmarkResultError",
    "BenchmarkRun",
    "BenchmarkRunner",
    "BenchmarkTaskEnvelope",
    "BenchmarkTaskError",
    "BenchmarkTaskEvaluatorIdentity",
    "BundleDeliveryResult",
    "CallableContractCompiler",
    "Candidate",
    "CandidateArchive",
    "CandidateBundleError",
    "CandidateDraft",
    "CandidateEvaluationError",
    "CandidateEvaluationResult",
    "CandidateEvaluationSpec",
    "CandidateEvaluatorPin",
    "CandidateExecution",
    "CandidateExecutionAdmission",
    "CandidateExecutionBudget",
    "CandidateExecutionError",
    "CandidateExecutionEvidenceError",
    "CandidateExecutionInput",
    "CandidateExecutionRecord",
    "CandidateExecutionRun",
    "CandidateExecutionRunner",
    "CandidateExecutionRunnerError",
    "CandidateGenerationBudget",
    "CandidateGenerationDiagnostic",
    "CandidateInputArtifact",
    "CandidateInputStagingError",
    "CandidateIntegrityAuthority",
    "CandidateReceipt",
    "CandidateRunner",
    "CandidateSourceBundle",
    "CandidateSourceFile",
    "CandidateWorkspaceError",
    "CandidateWorkspacePlan",
    "Checkpoint",
    "CommandAgentAdapter",
    "CommandCandidateEvaluator",
    "CommandCandidateGenerator",
    "CommandCandidateRunner",
    "ComparisonArm",
    "ComparisonArmResult",
    "CompilationQuestion",
    "CompilationResult",
    "ContractCandidateRunner",
    "ContractCompilationError",
    "ContractCompiler",
    "DataProfileError",
    "DeepEffectTrialConfig",
    "DeepEffectTrialRunner",
    "EffectAdapterError",
    "EffectKitError",
    "EffectPreflightError",
    "EffectPreflightReport",
    "EffectPreflightRunner",
    "EffectTrialConfig",
    "EffectTrialError",
    "EffectTrialReport",
    "EffectTrialRunner",
    "EvaluatorBundleError",
    "EvaluatorIdentity",
    "EvaluatorProfile",
    "EvaluatorReceipt",
    "EvolutionConfig",
    "EvolutionContext",
    "EvolutionError",
    "EvolutionStrategy",
    "ExecutionAwareCandidateEvaluator",
    "FeedbackError",
    "FrozenEvaluatorBundle",
    "GenerationRequest",
    "LoopStrategy",
    "ModelIdentity",
    "ModelProfile",
    "MultiFileCandidatePipeline",
    "OffspringOutcome",
    "OpenEvolveHandoffError",
    "OpenEvolveStrategy",
    "OutputSpec",
    "PhysicalAttemptBudget",
    "PopulationConfig",
    "PopulationState",
    "PopulationStrategy",
    "ProducerHandoffError",
    "ProducerMaterial",
    "ProducerResultEnvelope",
    "ProfileRegistry",
    "RejectedSeed",
    "RemoteCancelRequest",
    "RemoteContinueRequest",
    "RemoteEvolutionBackend",
    "RemoteEvolutionError",
    "RemoteExperimentReference",
    "RemoteExperimentState",
    "RemoteMaterialHandoffError",
    "RemoteMaterialReference",
    "RemoteStatusRequest",
    "RemoteSubmitRequest",
    "RemoteSyncRequest",
    "RuntimeAgentAdapter",
    "RuntimeContractCompiler",
    "SeedAdmissionError",
    "SeedAdmissionResult",
    "SeedIdentity",
    "SeedManifest",
    "SeedProvenance",
    "SeedRecord",
    "ShinkaHandoffError",
    "SolverProfile",
    "SolverScoringContract",
    "StagePolicy",
    "StagedCandidateExecutionInputs",
    "StagedRunResult",
    "StagedWorkflowConfig",
    "StagedWorkflowRunner",
    "StrategyResult",
    "TaskIdentity",
    "TaskInput",
    "TrialBaseline",
    "TrialSuite",
    "UsageLedger",
    "UsageSnapshot",
    "VerifiedCandidateExecutionAdmission",
    "VerifiedCandidateSourceBundle",
    "VerifiedCandidateWorkspace",
    "Worker",
    "WorkerAttempt",
    "WorkerOutcome",
    "WorkerPhase",
    "WorkerService",
    "WorkerStopReason",
    "WorkflowCheckpoint",
    "WorkflowCheckpointError",
    "WorkflowController",
    "WorkflowError",
    "WorkflowManifest",
    "WorkflowState",
    "admit_benchmark_comparison_plan",
    "admit_benchmark_comparison_result",
    "admit_benchmark_task_envelope",
    "admit_candidate_execution",
    "admit_candidate_execution_admission",
    "admit_openevolve_result",
    "admit_producer_envelope",
    "admit_producer_result",
    "admit_remote_materials",
    "admit_remote_state",
    "admit_seed_manifest",
    "benchmark_case_content_digest",
    "bind_benchmark_comparison_result_evidence",
    "build_algorithm_plan",
    "build_algorithm_role_plan",
    "build_candidate_execution_admission",
    "build_candidate_manifest",
    "build_candidate_workspace_plan",
    "build_effect_kit",
    "build_private_input_profile",
    "build_remote_producer_envelope",
    "build_round_feedback",
    "build_strategy",
    "candidate_file_table_sha256",
    "candidate_output_contract_sha256",
    "canonical_profile_json",
    "compile_evaluator_bundle",
    "compute_handoff_fingerprint",
    "compute_seed_identity",
    "config_from_contract",
    "contract_candidate_runner_fingerprint",
    "convert_fm_eval_baseline",
    "declared_producer_environment_sha256",
    "declared_protocol_environment_sha256",
    "evaluate_candidate_execution",
    "export_shinka_envelope",
    "export_shinka_result",
    "inspect_bundle_delivery",
    "inspect_candidate_evaluation",
    "inspect_candidate_execution_record",
    "load_bundle_pipeline",
    "load_evaluator_bundle",
    "materialize_candidate_source_bundle",
    "normalize_feedback",
    "parse_benchmark_comparison_plan",
    "parse_benchmark_comparison_result",
    "parse_benchmark_task_envelope",
    "parse_candidate_evaluation_report",
    "parse_candidate_evaluation_spec",
    "parse_candidate_execution_admission",
    "parse_candidate_source_bundle",
    "parse_candidate_workspace_plan",
    "parse_producer_envelope",
    "parse_seed_manifest",
    "prepare_producer_seed_manifest",
    "producer_bundle_dependency_sha256",
    "profile_sha256",
    "read_bundle_delivery_materials",
    "read_candidate_source_files",
    "reconcile_remote_state",
    "remote_cancel",
    "remote_continue_experiment",
    "remote_state_to_producer_envelope",
    "remote_status",
    "remote_submit",
    "remote_sync",
    "resolve_candidate_integrity_authority",
    "run_candidate_execution",
    "run_candidate_execution_recorded",
    "run_effect_preflight",
    "run_harness_adapter",
    "run_subject_adapter",
    "source_only_dependency_sha256",
    "stage_candidate_execution_inputs",
    "stage_candidate_inputs",
    "validate_benchmark_comparison_plan",
    "validate_candidate_execution_admission",
    "validate_candidate_source_bundle",
    "validate_candidate_workspace_plan",
    "verify_candidate_source_bundle",
]
