"""Standalone local Hermes-inspired agent controller."""

from .agent_evolution import (
    AgentCandidateEvaluator,
    AgentCandidateGenerator,
    AgentEvaluatorEnsemble,
    AgentPortfolioGenerator,
)
from .agents import (
    AgentAdapter,
    AgentError,
    AgentInvocationError,
    AgentRegistry,
    AgentRequest,
    AgentResult,
    AgentSelectionError,
    CommandAgentAdapter,
    RuntimeAgentAdapter,
)
from .algorithm import OutputSpec
from .benchmark import (
    BENCHMARK_STRATEGIES,
    BenchmarkConfig,
    BenchmarkError,
    BenchmarkReport,
    BenchmarkRun,
    BenchmarkRunner,
)
from .conversational import (
    CallableContractCompiler,
    CompilationQuestion,
    CompilationResult,
    ContractCompilationError,
    ContractCompiler,
    RuntimeContractCompiler,
    build_algorithm_plan,
    build_algorithm_role_plan,
)
from .evolution import (
    Candidate,
    CandidateArchive,
    CandidateDraft,
    CandidateExecution,
    CandidateRunner,
    CommandCandidateEvaluator,
    CommandCandidateGenerator,
    CommandCandidateRunner,
    EvolutionConfig,
    EvolutionContext,
    EvolutionError,
    EvolutionStrategy,
    ExecutionAwareCandidateEvaluator,
    GenerationRequest,
    LoopStrategy,
    OpenEvolveStrategy,
    PopulationConfig,
    PopulationState,
    PopulationStrategy,
    StrategyResult,
    build_strategy,
    config_from_contract,
)

__version__ = "0.1.0"

__all__ = [
    "BENCHMARK_STRATEGIES",
    "AgentAdapter",
    "AgentCandidateEvaluator",
    "AgentCandidateGenerator",
    "AgentError",
    "AgentEvaluatorEnsemble",
    "AgentInvocationError",
    "AgentPortfolioGenerator",
    "AgentRegistry",
    "AgentRequest",
    "AgentResult",
    "AgentSelectionError",
    "BenchmarkConfig",
    "BenchmarkError",
    "BenchmarkReport",
    "BenchmarkRun",
    "BenchmarkRunner",
    "CallableContractCompiler",
    "Candidate",
    "CandidateArchive",
    "CandidateDraft",
    "CandidateExecution",
    "CandidateRunner",
    "CommandAgentAdapter",
    "CommandCandidateEvaluator",
    "CommandCandidateGenerator",
    "CommandCandidateRunner",
    "CompilationQuestion",
    "CompilationResult",
    "ContractCompilationError",
    "ContractCompiler",
    "EvolutionConfig",
    "EvolutionContext",
    "EvolutionError",
    "EvolutionStrategy",
    "ExecutionAwareCandidateEvaluator",
    "GenerationRequest",
    "LoopStrategy",
    "OpenEvolveStrategy",
    "OutputSpec",
    "PopulationConfig",
    "PopulationState",
    "PopulationStrategy",
    "RuntimeAgentAdapter",
    "RuntimeContractCompiler",
    "StrategyResult",
    "build_algorithm_plan",
    "build_algorithm_role_plan",
    "build_strategy",
    "config_from_contract",
]
