"""Standalone local Hermes-inspired agent controller."""

from .agent_evolution import (
    AgentCandidateEvaluator,
    AgentCandidateGenerator,
    AgentEvaluatorEnsemble,
    AgentPortfolioGenerator,
)
from .agents import (
    AgentAdapter,
    AgentError,
    AgentInvocationError,
    AgentRegistry,
    AgentRequest,
    AgentResult,
    AgentSelectionError,
    CommandAgentAdapter,
    RuntimeAgentAdapter,
)
from .algorithm import OutputSpec
from .benchmark import (
    BENCHMARK_STRATEGIES,
    BenchmarkConfig,
    BenchmarkError,
    BenchmarkReport,
    BenchmarkRun,
    BenchmarkRunner,
)
from .conversational import (
    CallableContractCompiler,
    CompilationQuestion,
    CompilationResult,
    ContractCompilationError,
    ContractCompiler,
    RuntimeContractCompiler,
    build_algorithm_plan,
    build_algorithm_role_plan,
)
from .data_profile import (
    DataProfileError,
    build_private_input_profile,
    canonical_profile_json,
    profile_sha256,
)
from .deep_effect_trial import DeepEffectTrialConfig, DeepEffectTrialRunner
from .deep_feedback import (
    FeedbackError,
    build_candidate_manifest,
    build_round_feedback,
    normalize_feedback,
)
from .effect_adapters import (
    EffectAdapterError,
    convert_fm_eval_baseline,
    famou_case_content_digest,
    run_harness_adapter,
    run_subject_adapter,
)
from .effect_kit import EffectKitError, build_effect_kit
from .effect_preflight import (
    EffectPreflightError,
    EffectPreflightReport,
    EffectPreflightRunner,
    run_effect_preflight,
)
from .effect_trial import (
    BaselineProvenance,
    EffectTrialConfig,
    EffectTrialError,
    EffectTrialReport,
    EffectTrialRunner,
    TrialBaseline,
    TrialSuite,
)
from .evaluator_bundle import (
    EvaluatorBundleError,
    FrozenEvaluatorBundle,
    SolverScoringContract,
    compile_evaluator_bundle,
    load_evaluator_bundle,
)
from .evolution import (
    Candidate,
    CandidateArchive,
    CandidateDraft,
    CandidateExecution,
    CandidateInputArtifact,
    CandidateRunner,
    CommandCandidateEvaluator,
    CommandCandidateGenerator,
    CommandCandidateRunner,
    ContractCandidateRunner,
    EvolutionConfig,
    EvolutionContext,
    EvolutionError,
    EvolutionStrategy,
    ExecutionAwareCandidateEvaluator,
    GenerationRequest,
    LoopStrategy,
    OpenEvolveStrategy,
    PopulationConfig,
    PopulationState,
    PopulationStrategy,
    StrategyResult,
    build_strategy,
    config_from_contract,
    contract_candidate_runner_fingerprint,
    stage_candidate_inputs,
)
from .model_profile import UsageLedger, UsageSnapshot
from .profiles import EvaluatorProfile, ModelProfile, ProfileRegistry, SolverProfile
from .workflow_checkpoint import (
    AggregateUsage,
    Checkpoint,
    WorkflowCheckpoint,
    WorkflowCheckpointError,
    WorkflowController,
    WorkflowError,
    WorkflowManifest,
    WorkflowState,
)

__version__ = "0.1.0"

__all__ = [
    "BENCHMARK_STRATEGIES",
    "AgentAdapter",
    "AgentCandidateEvaluator",
    "AgentCandidateGenerator",
    "AgentError",
    "AgentEvaluatorEnsemble",
    "AgentInvocationError",
    "AgentPortfolioGenerator",
    "AgentRegistry",
    "AgentRequest",
    "AgentResult",
    "AgentSelectionError",
    "AggregateUsage",
    "BaselineProvenance",
    "BenchmarkConfig",
    "BenchmarkError",
    "BenchmarkReport",
    "BenchmarkRun",
    "BenchmarkRunner",
    "CallableContractCompiler",
    "Candidate",
    "CandidateArchive",
    "CandidateDraft",
    "CandidateExecution",
    "CandidateInputArtifact",
    "CandidateRunner",
    "Checkpoint",
    "CommandAgentAdapter",
    "CommandCandidateEvaluator",
    "CommandCandidateGenerator",
    "CommandCandidateRunner",
    "CompilationQuestion",
    "CompilationResult",
    "ContractCandidateRunner",
    "ContractCompilationError",
    "ContractCompiler",
    "DataProfileError",
    "DeepEffectTrialConfig",
    "DeepEffectTrialRunner",
    "EffectAdapterError",
    "EffectKitError",
    "EffectPreflightError",
    "EffectPreflightReport",
    "EffectPreflightRunner",
    "EffectTrialConfig",
    "EffectTrialError",
    "EffectTrialReport",
    "EffectTrialRunner",
    "EvaluatorBundleError",
    "EvaluatorProfile",
    "EvolutionConfig",
    "EvolutionContext",
    "EvolutionError",
    "EvolutionStrategy",
    "ExecutionAwareCandidateEvaluator",
    "FeedbackError",
    "FrozenEvaluatorBundle",
    "GenerationRequest",
    "LoopStrategy",
    "ModelProfile",
    "OpenEvolveStrategy",
    "OutputSpec",
    "PopulationConfig",
    "PopulationState",
    "PopulationStrategy",
    "ProfileRegistry",
    "RuntimeAgentAdapter",
    "RuntimeContractCompiler",
    "SolverProfile",
    "SolverScoringContract",
    "StrategyResult",
    "TrialBaseline",
    "TrialSuite",
    "UsageLedger",
    "UsageSnapshot",
    "WorkflowCheckpoint",
    "WorkflowCheckpointError",
    "WorkflowController",
    "WorkflowError",
    "WorkflowManifest",
    "WorkflowState",
    "build_algorithm_plan",
    "build_algorithm_role_plan",
    "build_candidate_manifest",
    "build_effect_kit",
    "build_private_input_profile",
    "build_round_feedback",
    "build_strategy",
    "canonical_profile_json",
    "compile_evaluator_bundle",
    "config_from_contract",
    "contract_candidate_runner_fingerprint",
    "convert_fm_eval_baseline",
    "famou_case_content_digest",
    "load_evaluator_bundle",
    "normalize_feedback",
    "profile_sha256",
    "run_effect_preflight",
    "run_harness_adapter",
    "run_subject_adapter",
    "stage_candidate_inputs",
]
